version: "3.8"
services:
  database:
    image: postgres:12.4-alpine
    volumes:
      - dbdata:/var/lib/postgresql/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/postgresql/data
      POSTGRES_DB: db_queens
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - 1000:5432
  nqueens:
    build: ./nqueens
    working_dir: /var/www/nqueens
    command: /bin/sh -c "flask run --host=0.0.0.0"
    volumes:
      - ./nqueens/.:/var/www/nqueens
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: db_queens
      DB_USERNAME: db_user
      DB_PASSWORD: db_password
      FLASK_APP: main.py
      FLASK_ENV: development
      HOST: 0.0.0.0
      PORT: 5000
      DEBUG: "true"
    depends_on:
      - database
    ports: 
      - 1001:5000
volumes:
  dbdata:
