version: "3.8"
services:
  database:
    image: postgres:12.4-alpine
    volumes:
      - dbdata:/var/lib/postgresql/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/postgresql/data
      POSTGRES_DB: db_queens
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - 1000:5432
  queens:
    build: ./generator
    working_dir: /var/www/queens
    volumes:
      - ./generator/.:/var/www/queens
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: db_queens
      DB_USERNAME: db_user
      DB_PASSWORD: db_password
    depends_on:
      - database
volumes:
  dbdata:
