name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-suite:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run the test with docker-compose
    run: docker-compose run queens python -m pytest tests_solution2.py