name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-suite:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initialize docker
      run: docker-compose up -d
    - name: Initilize database
      run: docker-compose run nqueens flask initdb
    - name: Run the test with docker-compose
      run: docker-compose run nqueens python -m pytest app/tests/tests.py
    - name: Run proposed tests without store it in database
      run: docker-compose run nqueens python -m pytest app/tests/tests_solutions_not_saving.py
    - name: Run proposed tests and store it in database
      run: docker-compose run nqueens python -m pytest app/tests/tests_solutions.py
    - name: Run to test stored solutions
      run: docker-compose run nqueens python -m pytest app/tests/tests_solutions_stored.py
